#include <iostream>
#include <stdlib.h>
#include <ctime>

using namespace std;
void rules();
int main()
{
    char choice;
    int guess, number, k=0;
    string playerName;
    srand(time(0));
    cout << "\n\t\t========WELCOME TO RNG WORLD=======\n\n";
    cout << "\n\nWhat`s your name :"; getline(cin, playerName);
    do {
        system("cls");
        rules();
        number = rand()%99+1;
        cout << "\n\nHello " << playerName << " please introduce a number between 1 and 100: "; cin >> guess;
        do {
            if(guess <=1 || guess>=100)
                cout << "\nGuess should be between 1 and 100\n Please re-enter guess:\n";
            else if(guess>number) {
                cout << "\nThe number you guessed is bigger than the original number\n Please try again: ";
                cin >> guess;
                k++;
            }
            else if(guess<number) {
                cout << "\nThe number you guessed is smaller than the original number\n Please try again: ";
                cin >> guess;
                k++;
            }
        }while(guess!=number);
        cout << "\nCongratulations! You guessed the number in " << k << " tries\n" << "Do you want to play again (y/n)?";
        cin >> choice;
    }while(choice=='y' || choice=='Y');
    cout << "\n\n\n";
    cout << "\n\nThanks for playing the game.\n\n";
    return 0;
}

void rules() {
    cout << "\t\t======RANDOM NUMBER GUESSING RULES!======\n";
    cout << "\tAll you have to do is guess the random number generated by the computer.";
}
